version: '3.8'

services:
  mariadb:
    image: mariadb:v1
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - net_inception
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

  wordpress:
    image: wordpress:v1
    container_name: wordpress
    build: ./requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - net_inception
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    image: nginx:v1
    container_name: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress_data:/var/www/html/wordpress:ro
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - net_inception
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: 'curl -kfsSL https://localhost:443/status'
      interval: 5s
      timeout: 1s
      retries: 10
      start_period: 5s

networks:
  net_inception:
  
volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wordpress_data: