FROM debian:bullseye

ENV DEBIAN_FRONTEND=noninteractive

# install NGINX and other dependencies
RUN apt-get update -y 
RUN apt-get install -y nginx
RUN apt-get install -y vim
RUN apt-get install -y curl
RUN mkdir -p /etc/nginx/ssl
RUN apt-get install -y openssl
RUN mkdir -p /etc/nginx/ssl

# 1)create a directory to store certificates and keys 2)generate the keys
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception_key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42Paris/CN=ayael-ou.42.fr/UID=ayael-ou"

RUN mkdir -p /var/run/nginx

# copy the provided config file to the container
COPY ./conf/nginx.conf /etc/nginx/nginx.conf

# RUN chmod 755 /var/www/html/ && \
#     chown -R www-data:www-data /var/www/html/

RUN chmod 755 /var/www/html
RUN chown -R www-data:www-data /var/www/html
    
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
